---
# tasks file for common
- name: Include task list for checking common tools installed
  import_tasks: setupTool.yml
  
- name: Include task list for tuning System
  import_tasks: tuningSystem.yml
